# Generated by Django 5.1.6 on 2025-06-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PadelRDB_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racket',
            old_name='sweetspot',
            new_name='balance',
        ),
    ]
